# Generated by Django 2.1.1 on 2018-10-27 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0002_auto_20181027_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_play', to='mastermind.Game', verbose_name='Related game'),
            preserve_default=False,
        ),
    ]
