# Generated by Django 2.1.1 on 2018-10-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0003_play_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='first_feedback',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='fourth_feedback',
            new_name='fourth',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='second_feedback',
            new_name='second',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='third_feedback',
            new_name='third',
        ),
    ]
