# Generated by Django 2.1.1 on 2018-10-27 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0004_auto_20181027_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='codebreaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codebreaker_game', to=settings.AUTH_USER_MODEL, verbose_name='Code Breaker'),
        ),
        migrations.AlterField(
            model_name='game',
            name='codemaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codemaker_game', to=settings.AUTH_USER_MODEL, verbose_name='Code Maker'),
        ),
        migrations.AlterField(
            model_name='game',
            name='secret_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_code_game', to='mastermind.Code', verbose_name='Secret code'),
        ),
    ]
